import { BadRequestException, Injectable } from '@nestjs/common'; import { InjectModel } from '@nestjs/mongoose'; import { Model } from 'mongoose'; import { CatalogQueryDto } from './dto/catalog-query.dto';
interface CatalogRecord { id:string; catalogVersion:number; [key:string]:unknown }
interface BranchRecord { id:string; currentCatalogVersion:number }
type Kind='categories'|'products'|'productUnits'|'productPrices';
@Injectable() export class CatalogService {
  constructor(@InjectModel('Branch') private readonly branches:Model<BranchRecord>,@InjectModel('Category') private readonly categories:Model<CatalogRecord>,@InjectModel('Product') private readonly products:Model<CatalogRecord>,@InjectModel('ProductUnit') private readonly units:Model<CatalogRecord>,@InjectModel('ProductPrice') private readonly prices:Model<CatalogRecord>){}
  async pull(query:CatalogQueryDto){ const branch=await this.branches.findOne({id:query.branchId,deletedAt:null}).lean().exec(); if(!branch) throw new BadRequestException('Unknown branch'); const offset=this.decodeCursor(query.cursor); const filter={branchId:query.branchId,catalogVersion:{$gt:query.catalogVersion}}; const groups=await Promise.all([this.categories.find(filter).select('-_id -__v').lean().exec(),this.products.find(filter).select('-_id -__v').lean().exec(),this.units.find(filter).select('-_id -__v').lean().exec(),this.prices.find(filter).select('-_id -__v').lean().exec()]); const kinds:Kind[]=['categories','products','productUnits','productPrices']; const combined=groups.flatMap((records,index)=>records.map(record=>({kind:kinds[index],record}))).sort((a,b)=>a.record.catalogVersion-b.record.catalogVersion||a.kind.localeCompare(b.kind)||a.record.id.localeCompare(b.record.id)); const page=combined.slice(offset,offset+query.limit); const response:{catalogVersion:number;hasMore:boolean;cursor?:string;categories:CatalogRecord[];products:CatalogRecord[];productUnits:CatalogRecord[];productPrices:CatalogRecord[]}={catalogVersion:branch.currentCatalogVersion,hasMore:offset+query.limit<combined.length,categories:[],products:[],productUnits:[],productPrices:[]}; for(const item of page) response[item.kind].push(item.record); if(response.hasMore) response.cursor=this.encodeCursor(offset+query.limit); return response; }
  private encodeCursor(offset:number){return Buffer.from(String(offset)).toString('base64url');} private decodeCursor(cursor?:string){if(!cursor)return 0; const value=Number(Buffer.from(cursor,'base64url').toString()); if(!Number.isInteger(value)||value<0)throw new BadRequestException('Invalid cursor'); return value;}
}
